spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Focstrotnoob/Config-Server.git
          clone-on-start: true
          search-paths:
            - 'configs/{application}/{profile}'

server:
  port: 8888